# pull official base image
FROM python:3.6-slim-buster

COPY requirements_labeler.txt .

# install system dependencies
RUN apt-get update \
  && apt-get -y install netcat gcc \
  && apt-get clean

RUN pip install -r requirements_labeler.txt

RUN adduser -disabled-password labeler

# set working directory
WORKDIR /home/labeler

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1