# pull official base image
FROM postgres:13-alpine

# run create.sql on init
ADD create.sql /docker-entrypoint-initdb.d

#WORKDIR /home/db

#COPY db .

# run create.sql on init
#ADD create.sql /docker-entrypoint-initdb.d